name: ghc-bones
version: 0.0.1
category: Compiler, Development
synopsis: A wrapper of GHC API to help reuse the frontend.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/ghc-bones

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md
  - test/case/*.hs

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10
  - ghc
  - ghc-paths
  - monad-control
  - mtl
  - safe-exceptions
  - transformers-base

library:
  source-dirs: src

tests:
  test:
    main: Main.hs
    other-modules: []
    ghc-options: -threaded -feager-blackholing -with-rtsopts=-N
    source-dirs:
      - test
    dependencies:
      - ghc-bones
      - tasty
      - tasty-hunit
